### ISSUE TITLE
JS Error: Navigation links

### ISSUE THREAD

**Issue by virginiacc** [cfpb/regulations-site#815]
In IE,  an error sometimes occurs when the navigation links at the bottom of the main section are clicked. It does not seem to affect user experience.

__Stack trace:__
```
TypeError: Unable to get property 'length' of undefined or null reference
   at openSection (http://www.consumerfinance.gov/static/regulations/js/built/regulations.min.js:6:23866)
   at ea.event.dispatch (http://www.consumerfinance.gov/static/regulations/js/built/regulations.min.js:3:24226)
   at q.handle (http://www.consumerfinance.gov/static/regulations/js/built/regulations.min.js:3:20879)
```

__To replicate:__ 
- In IE11, navigate to http://www.consumerfinance.gov/eregulations/1026-38/2016-06834 
- Use the navigation links at the bottom of the main section to move back and forth between 1026.38 and 1026.37. The error appears on 1026.37.

![b69e22fa-5f9b-11e6-93aa-187b289503c7](https://cloud.githubusercontent.com/assets/778171/18040079/78d5ec2a-6d5e-11e6-98f7-cfd0dce3a22c.png)

**Comment by ascott1** [comment]
Great catch @virginiacc!
