### ISSUE TITLE
JS Error: Section title on scroll

### ISSUE THREAD

**Issue by virginiacc** [cfpb/regulations-site#816]
In IE,  an error sometimes occurs when scrolling down the page. It does not seem to affect user experience.

__Stack trace:__
```
TypeError: Unable to get property 'split' of undefined or null reference
   at b.exports.idToRef (http://www.consumerfinance.gov/static/regulations/js/built/regulations.min.js:5:25017)
   at changeTitle (http://www.consumerfinance.gov/static/regulations/js/built/regulations.min.js:6:11408)
   at n (http://www.consumerfinance.gov/static/regulations/js/built/regulations.min.js:1:21743)
   at b.Events.trigger (http://www.consumerfinance.gov/static/regulations/js/built/regulations.min.js:1:21101)
   at checkActiveSection (http://www.consumerfinance.gov/static/regulations/js/built/regulations.min.js:6:14231)
   at ea.event.dispatch (http://www.consumerfinance.gov/static/regulations/js/built/regulations.min.js:3:24226)
   at Anonymous function (http://www.consumerfinance.gov/static/regulations/js/built/regulations.min.js:5:23549)
```

__To replicate:__ 
- In IE11, navigate to http://www.consumerfinance.gov/eregulations/1026-38/2016-06834 
- Scroll down the page. The error will occur as the section title updates based on the current scroll position.  
![cb5e0b3e-5f9a-11e6-9f95-1c2969cf413f](https://cloud.githubusercontent.com/assets/778171/18040139/1a418682-6d5f-11e6-91c9-1d2ac9062b76.png)

**Comment by ascott1** [comment]
Great catch @virginiacc! Thank you.
